version: '3.8'

services:
  baget:
    image: loicsharma/baget
    container_name: baget
    ports:
      - "5555:80"
    volumes:
      - ./baget-data:/var/baget
    environment:
      - ApiKey__IsRequired=false
      - Storage__Type=FileSystem
      - Storage__Path=/var/baget/packages
      - Database__Type=PostgreSql
      - Database__ConnectionString=Host=postgres;Port=5432;Database=baget;Username=baget;Password=baget_password
      - Search__Type=Database
    networks:
      - baget-network
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=baget
      - POSTGRES_PASSWORD=baget_password
      - POSTGRES_DB=baget
    ports:
      - "5432:5432"      
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - baget-network

volumes:
  postgres-data:

networks:
  baget-network:
    driver: bridge